# This is a basic workflow to help you get started with Actions

name: CI devops 2021 EPF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: build-and-test-app
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.3.3
        run: git checkout
        
      - name: Set up JDK 11
          with:
    distribution: 'zulu'
    java-version: '11'
      - run: java -cp java HelloWorldApp
      
      - name: Build and test with Maven
        run: mvn clean verify
 

