# This is a basic workflow to help you get started with Actions

name: CI devops 2021 EPF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
jobs: 
  build-and-test-app:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.3.3
        
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      
      - name: Build and test with Maven
        run: mvn -B package --file ./simple-api
 

